project_name: CUB200-T2
exp_name: T3000
use_wandb: False
wandb_entity: haoyanfang
train_root1: /media/haoyanfang/Student/HaoYanFang/CMAL/data/Data_分型/train/
val_root1: /media/haoyanfang/Student/HaoYanFang/CMAL/data/Data_分型/test/
train_root: ./breast_data/Her2/train/
val_root: ./breast_data/分型/test/
data_size: 256
num_workers: 2
batch_size: 1
model_name: resnet50
pretrained: ~
optimizer: SGD
max_lr: 0.0001
wdecay: 0.0005
max_epochs: 200
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 4
num_selects:
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 5
device: cuda